FROM php:7.0-apache
MAINTAINER Ichsarut Yauvasuta <ichsarut@gmail.com>

RUN apt-get update && apt-get install -y \
  libfreetype6-dev \
  libjpeg62-turbo-dev \ 
  libmcrypt-dev \
  libpng12-dev \
	libmemcached-dev \
  libmysqlclient-dev \
	libicu-dev \
  libpq-dev \
	curl \
  && docker-php-ext-install iconv mcrypt \
  && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
  && docker-php-ext-install gd \
  && docker-php-ext-install mbstring \

RUN docker-php-ext-enable redis \
  && echo 'redis' >> /usr/src/php-available-exts \
  && echo "extension=redis.so" > /usr/local/etc/php/conf.d/redis.ini


    
