version: '2'

php:
    image: php:7.1-fpm-alpine
    #build: php
    networks:
      - internal_network
    volumes:
      - ../html:/var/www/html
    restart: always
redis:
    image: redis:4-alpine
    environment:
      #- REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PASSWORD=YOUR_REDIS_PASSWORD
    command: redis-server --appendonly yes
    volumes:
      - ../data/redis:/data
    networks:
      - internal_network
nginx:
    image: nginx:1-alpine
    ports:   #only if traefik is disabled
     - 80:80 #only if traefik is disabled
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - ./nginx/conf.d:/etc/nginx/conf.d
     - ../html:/var/www/html
    networks:
     - internal_network
     - external_network