FROM php:7.0-apache
RUN pecl install redis && docker-php-ext-enable redis


RUN echo "extension=redis.so" > /etc/php/7.0/mods-available/redis.ini \
  && ln -sf /etc/php/7.0/mods-available/redis.ini /etc/php/7.0/fpm/conf.d/20-redis.ini \
  && ln -sf /etc/php/7.0/mods-available/redis.ini /etc/php/7.0/cli/conf.d/20-redis.ini \
  apache2ctl restart