version: '2'

services:
  web:
    container_name : redis-web
    build: .
    ports:
      - 9080:80
    volumes:
      - ./src/html:/var/www/html/
    links:
      - redis
  redis:
    image: "redis:alpine"
  mysql: 
    container_name : redis-mysql
    image: mysql:latest
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: myDB
      MYSQL_USER: root
      MYSQL_PASSWORD: 212224
      MYSQL_ROOT_PASSWORD: 212224
    ports: 
      - "33066:3306"

      