version: '2'

services:
  web:
    build: .
    port: 
      - "8001:80"
    volumes:
      - ./src/html:/var/www/html/
    links:
      - redis:devcache1
  redis:
    image: "redis:alpine"
  db: 
    image: mysql
      environment:
        - "MYSQL_ROOT_PASSWORD=secret"
        - "MYSQL_DATABASE=redis"
      ports: 
        - "33061:3306"