# FROM php:7.0-apache
# MAINTAINER Ichsarut Yauvasuta <ichsarut@gmail.com>

# RUN pecl install redis && docker-php-ext-enable redis \
#   && echo 'redis' >> /usr/src/php-available-exts \
#   && docker-php-ext-install redis \
#   && echo "extension=redis.so" > /usr/local/etc/php/conf.d/redis.ini
FROM php:7.1-fpm
RUN pecl install redis-3.1.0 \
    && pecl install xdebug-2.5.0 \
    && docker-php-ext-enable redis xdebug
    
