FROM php:7.0-apache
MAINTAINER Ichsarut Yauvasuta <ichsarut@gmail.com>
RUN pecl install redis && docker-php-ext-enable redis


# RUN apt-get update && apt-get install -y \
#         libfreetype6-dev \
#         libjpeg62-turbo-dev \
#         libmcrypt-dev \
#         libpng12-dev \
# 	      libmemcached-dev \
#         libmysqlclient-dev \
# 	      libicu-dev \
#         libpq-dev \
# 	      curl \
#     && docker-php-ext-install iconv mcrypt \
#     && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
#     && docker-php-ext-install gd \
#     && docker-php-ext-install mbstring \
#     && docker-php-ext-install mysqli \
#     && docker-php-ext-install pdo_mysql \
#     && docker-php-ext-install intl \
#     && docker-php-ext-install pdo_pgsql \
#     && mkdir -p /usr/src/php/ext/redis \
#     && curl -L https://github.com/phpredis/phpredis/archive/3.0.0.tar.gz | tar xvz -C /usr/src/php/ext/redis --strip 1 \
#     && echo 'redis' >> /usr/src/php-available-exts \
#     && docker-php-ext-install redis




    
