FROM php:7.0-apache
MAINTAINER Ichsarut Yauvasuta <ichsarut@gmail.com>

RUN pecl install redis && docker-php-ext-enable redis \
  && echo 'redis' >> /usr/src/php-available-exts \
  && docker-php-ext-install redis



    
