FROM php:7.0-apache
# mount directory  
COPY src/html/ /var/www/html/ 
# mount conf file
COPY config/apache-config.conf /usr/local/etc/php/

RUN pecl install redis-3.1.0 \
    && pecl install xdebug-2.5.0 \
    && docker-php-ext-enable redis xdebug