version: '3'

php:
    image: .
    networks:
      - internal_network
    volumes:
      - ./src/html:/var/www/html
    restart: always
redis:
    image: redis:4-alpine
    environment:
      #- REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PASSWORD=212224
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data
    networks:
      - internal_network
nginx:
    image: nginx:1-alpine
    ports:   #only if traefik is disabled
     - 80:80 #only if traefik is disabled
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - ./nginx/conf.d:/etc/nginx/conf.d
     - ../html:/var/www/html
    networks:
     - internal_network
     - external_network