version: '2'

services:
  web:
    build: .
    expose: 9000
    volumes:
      - ./src/html:/var/www/html/
    links:
      - redis
  redis:
    image: "redis:alpine"
  db: 
    image: mysql:latest
    environment:
      MYSQL_DATABASE: myDB
      MYSQL_USER: root
      MYSQL_PASSWORD: 212224
      MYSQL_ROOT_PASSWORD: 212224
    ports: 
      - "33061:3306"

      